{% set name = "kaldi-native-fbank" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: 
  sha256: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - cmake
    - pip
  run:
    - python

test:
  imports:
    - kaldi_native_fbank
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/csukuangfj/kaldi-native-fbank
  summary: Kaldi-compatible online fbank feature extractor without external dependencies.
  description: Kaldi-compatible online fbank feature extractor without external dependencies.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/csukuangfj/kaldi-native-fbank
  dev_url: https://github.com/csukuangfj/kaldi-native-fbank

extra:
  recipe-maintainers:
    - boldorider4
