{% set name = "kaldi-native-fbank" %}
{% set version = "1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b877a6aea7b09f87dfefd9e01106f38221287a2369fcda9221beb6bb76476d5c
  patches:
    - 0001-unvendor-gtest-and-pybind11.patch
    - 0002-install-cmake-config-for-package.patch
    - 0003-Update-ExtractWindow-signature.patch

build:
  number: 0
  ignore_run_exports:
    - gtest
  missing_dso_whitelist:
    - $RPATH/ld64.so.*  # [s390x]
    - $RPATH/libkaldi-native-fbank-core.dylib  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make # [not win]
    - ninja
    - git  # [not win]
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - pybind11 2.12.0
    - gtest 1.14.0
  run:
    - python
    # part of the targets that are build are test-log, test-online-fbank and test-rfft which link to gtest libraries
    - gtest

test:
  imports:
    - kaldi_native_fbank
  commands:
    - pip check
    - test-log | grep PASSED
    - test-online-fbank
    - test-rfft | grep PASSED
  requires:
    - pip

about:
  home: https://github.com/csukuangfj/kaldi-native-fbank
  summary: Kaldi-compatible online fbank feature extractor without external dependencies.
  description: Kaldi-compatible online fbank feature extractor without external dependencies.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/csukuangfj/kaldi-native-fbank
  dev_url: https://github.com/csukuangfj/kaldi-native-fbank

extra:
  recipe-maintainers:
    - boldorider4
